name = "1.20.1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fbf62d7351636ca01b153c37eead8a6168a8acbb179741a3a566ef8fcde3375a"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
