name = "Technological-Ascent"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abde3c0629d2760ac3f44aecbde28a6c01d81be0175e2dd613259a78950da046"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
