ServerEvents.recipes(event => {
    event.remove({ output: 'ae2:crystal_resonance_generator' })
    event.remove({ id: 'ae2:blasting/sky_stone_block' })
    event.remove({ id: 'enderio:smelting/ae2/blasting/sky_stone_block' })
    event.remove({ id: 'expatternprovider:cutter/accumulation' })
    event.remove({ id: 'mekmm:compat/megacells/stamper/printed_accumulation_processor' })
    event.remove({ id: 'megacells:inscriber/accumulation_processor_print' })
    event.remove({ id: 'appflux:smelting/harden_resin' })
    event.remove({ id: 'appflux:blasting/harden_resin' })
    event.remove({ id: 'ae2:network/wireless_part' })
    event.remove({ id: 'enderio:smelting/appflux/smelting/harden_resin' })
    event.remove({ id: 'advanced_ae:chargedredstone' })
    event.remove({ id: 'appflux:charger/charge_redstone' })
    event.remove({ output: 'ae2:spatial_storage_cell_2' })
    event.remove({ output: 'ae2:spatial_storage_cell_16' })
    event.remove({ output: 'ae2:spatial_storage_cell_128' })
    event.remove({ output: 'ae2:spatial_io_port' })
    event.remove({ id: 'megacells:crafting/greater_energy_card' })
})