ServerEvents.recipes(event => {
  function RemoveID(id) {event.remove({ id: id })}; function RemoveType(type) {event.remove({ type: type })}; function RemoveOutput(output) {event.remove({ output: output })}

  const ids = ['botania:alchemy_catalyst','botania:runic_altar/mana','botania:runic_altar/water','botania:runic_altar/air','botania:runic_altar/fire','botania:runic_altar/earth',
    'tconstruct:smeltery/casting/seared/smeltery_controller','createaddition:compacting/seed_oil','createaddition:liquid_burning/diesel','createaddition:liquid_burning/biofuel',
    'createaddition:liquid_burning/gasoline','createaddition:liquid_burning/biodiesel','projecte:low_covalence_dust','projecte:medium_covalence_dust','projecte:high_covalence_dust',
    'botania:glimmering_stripped_livingwood','botania:glimmering_stripped_livingwood_log','botania:glimmering_livingwood','botania:glimmering_livingwood_log','botania:alfheim_portal',
    'botania:natura_pylon','expatternprovider:circuit_cutter','industrialforegoing:laser_drill_ore/quartz','industrialforegoing:laser_drill_ore/raw_materials/nickel',
    'industrialforegoing:laser_drill_ore/ores/ruby','industrialforegoing:laser_drill_ore/raw_materials/iron','industrialforegoing:laser_drill_ore/raw_materials/copper',
    'industrialforegoing:laser_drill_ore/raw_materials/gold','industrialforegoing:laser_drill_ore/raw_materials/silver','industrialforegoing:laser_drill_ore/ores/sapphire',
    'industrialforegoing:laser_drill_ore/ores/cinnabar','industrialforegoing:laser_drill_ore/raw_materials/tin','industrialforegoing:laser_drill_ore/raw_materials/lead',
    'industrialforegoing:laser_drill_ore/ores/sulfur','industrialforegoing:laser_drill_ore/ores/niter','industrialforegoing:laser_drill_ore/emerald',
    'industrialforegoing:laser_drill_ore/ancient_debris','industrialforegoing:laser_drill_ore/glowstone','industrialforegoing:laser_drill_ore/diamond',
    'industrialforegoing:laser_drill_ore/coal','industrialforegoing:laser_drill_ore/redstone','industrialforegoing:laser_drill_ore/lapis',
    'ifeu:shaped/fluid_transfer','thermal:furnace_2010439657','pneumaticcraft:thermo_plant/reinforced_pressure_tube','industrialforegoing:fluid_extractor',
    'industrialforegoing:latex_processing_unit','pneumaticcraft:heat_frame_cooling/plastic','projecte:iron_band','industrialforegoing:mob_slaughter_factory','entangled:block',
    'thermal:bronze_dust_4','thermal:fire_charge/bronze_ingot_4','thermal:electrum_dust_2','thermal:fire_charge/electrum_ingot_2','thermal:invar_dust_3',
    'thermal:fire_charge/invar_ingot_3','thermal:constantan_dust_2','thermal:fire_charge/constantan_ingot_2','thermal:signalum_dust_4','thermal:fire_charge/signalum_ingot_4',
    'thermal:lumium_dust_4','thermal:fire_charge/lumium_ingot_4','thermal:enderium_dust_2','thermal:fire_charge/enderium_ingot_2','thermal:machine_frame','createaddition:mixing/electrum',
    'thermal:fire_charge/obsidian_glass_2','thermal:fire_charge/signalum_glass_2','thermal:fire_charge/lumium_glass_2','thermal:fire_charge/enderium_glass_2',
    'industrialforegoing:laser_drill_ore/raw_materials/osmium','industrialforegoing:laser_drill_ore/ores/fluorite','industrialforegoing:laser_drill_ore/raw_materials/uranium',
    'industrialforegoing:laser_drill_ore/ores/draconium','rftoolsbase:machine_frame','rftoolsbase:machine_base','laserio:logic_chip','thermal:furnace_1842703880',
    'powah:crafting/dielectric_casing','gardenofglass:end_portal_frame','gag:time_sand_pouch','mekanism:steel_casing','pneumaticcraft:thermo_plant/plastic_from_biodiesel',
    'pneumaticcraft:thermo_plant/plastic_from_lpg','pneumaticcraft:explosion_crafting/compressed_iron_ingot','pneumaticcraft:explosion_crafting/compressed_iron_block',
    'pneumaticcraft:pressure_chamber/compressed_iron_block','pneumaticcraft:pressure_chamber/compressed_iron_ingot','pneumaticcraft:speed_upgrade',
    'pneumaticcraft:speed_upgrade_from_glycerol','pneumaticcraft:thermo_plant/lubricant_from_biodiesel','pneumaticcraft:amadron/emerald_to_lubricant',
    'draconicevolution:machines/basic_crafting_injector','draconicevolution:machines/crafting_core','mekanism:cardboard_box','mekanism:processing/uranium/fissile_fuel',
    'ifeu:dissolution_chamber/empty_nether_star','ifeu:dissolution_chamber/rough_dragon_star','ifeu:dissolution_chamber/nether_star','minecraft:netherite_upgrade_smithing_template',
    'avaritia:eternal_singularity','extendedcrafting:ultimate_table','extendedcrafting:the_ultimate_component','avaritia:ultimate_stew','avaritia:mek_creative_fluid_tank',
    'avaritia:mek_creative_energy_cube','avaritia:mek_creative_bin','avaritia:botania_mana_tablet','avaritia:de_creative_op_capacitor','avaritia:ae2_creative_energy_cell',
    'avaritia:de_creative_capacitor','avaritia:upgrade_smithing_template','avaritia:mek_creative_chemical_tank','avaritia:botania_creative_pool','ifeu:sculk_gear',
    'mekanism:crushing/charcoal_dust','mekanism:compat/ae2/certus_crystal_to_dust','mekanism:compat/ae2/fluix_crystal_to_dust','mekanism:compat/ae2/sky_stone_to_dust',
    'mekanism:processing/fluorite/to_dust','thermal:compat/mekanism/pulverizer_mek_fluorite','mekanism:processing/coal/to_dust','create:crushing/obsidian',
    'mekanism:processing/refined_obsidian/dust/from_ingot','mekanism:processing/osmium/dust/from_ingot','mekanism:processing/uranium/dust/from_ingot',
    'thermalendergy:machine/pulverizer/pulverizer_prismalium_ingot_to_dust','thermalendergy:machine/pulverizer/pulverizer_melodium_ingot_to_dust',
    'thermalendergy:machine/pulverizer/pulverizer_stellarium_ingot_to_dust','thermal:machines/pulverizer/pulverizer_apatite','thermal:machines/pulverizer/pulverizer_cinnabar',
    'thermal:machines/pulverizer/pulverizer_niter','thermal:machines/pulverizer/pulverizer_sulfur','thermal:machines/pulverizer/pulverizer_ender_pearl',
    'mekanism:processing/iron/dust/from_ingot','thermal:machines/pulverizer/pulverizer_iron_ingot_to_dust','mekanism:processing/gold/dust/from_ingot',
    'thermal:machines/pulverizer/pulverizer_gold_ingot_to_dust','mekanism:processing/copper/dust/from_ingot','thermal:machines/pulverizer/pulverizer_copper_ingot_to_dust',
    'mekanism:processing/netherite/ingot_to_dust','thermal:machines/pulverizer/pulverizer_netherite_ingot_to_dust','mekanism:processing/tin/dust/from_ingot',
    'thermal:machines/pulverizer/pulverizer_tin_ingot_to_dust','mekanism:processing/lead/dust/from_ingot','thermal:machines/pulverizer/pulverizer_lead_ingot_to_dust',
    'thermal:machines/pulverizer/pulverizer_silver_ingot_to_dust','thermal:machines/pulverizer/pulverizer_nickel_ingot_to_dust','mekanism:processing/lapis_lazuli/to_dust',
    'thermal:machines/pulverizer/pulverizer_lapis','createaddition:crushing/diamond','mekanism:processing/diamond/to_dust','thermal:machines/pulverizer/pulverizer_diamond',
    'mekanism:processing/emerald/to_dust','thermal:machines/pulverizer/pulverizer_emerald','mekanism:processing/quartz/to_dust','thermal:machines/pulverizer/pulverizer_quartz',
    'mekanism:processing/tin/storage_blocks/from_ingots','mekanism:processing/tin/raw_storage_blocks/from_raw','mekanism:processing/lead/storage_blocks/from_ingots',
    'mekanism:processing/lead/raw_storage_blocks/from_raw','mekanism:storage_blocks/steel','mekanism:storage_blocks/bronze','createaddition:crafting/electrum_block',
    'avaritia:neutron_gear','create:blasting/ingot_lead_compat_mekanism','create:blasting/ingot_tin_compat_mekanism','mekanism:processing/tin/ingot/from_raw_blasting',
    'mekanism:processing/lead/ingot/from_raw_blasting','industrialforegoing:laser_drill_fluid/lava','mekanism:processing/steel/ingot/from_dust_blasting',
    'mekanism:processing/bronze/ingot/from_dust_blasting','functionalstorage:netherite_upgrade','create:crafting/materials/copper_nugget','pneumaticcraft:copper_nugget',
    'mekanism:processing/tin/nugget/from_ingot','mekanism:processing/lead/nugget/from_ingot','mekanism:nuggets/steel','mekanism:nuggets/bronze','createaddition:crafting/electrum_nugget',
    'thermal:compat/create/smelter_create_alloy_chromatic_compound','createsifter:sifting/soul_sand_advanced_brass_mesh','mekanism:processing/steel/ingot_to_dust',
    'thermal:machines/pulverizer/pulverizer_steel_ingot_to_dust','thermal:machines/pulverizer/pulverizer_rose_gold_ingot_to_dust','mekanism:processing/bronze/dust/from_ingot',
    'thermal:machines/pulverizer/pulverizer_bronze_ingot_to_dust','thermal:machines/pulverizer/pulverizer_electrum_ingot_to_dust',
    'thermal:machines/pulverizer/pulverizer_invar_ingot_to_dust','thermal:machines/pulverizer/pulverizer_constantan_ingot_to_dust',
    'thermal:machines/pulverizer/pulverizer_signalum_ingot_to_dust','thermal:machines/pulverizer/pulverizer_lumium_ingot_to_dust',
    'thermal:machines/pulverizer/pulverizer_enderium_ingot_to_dust','pneumaticcraft:amadron/pcb_blueprint','thermal:compat/create/bottler_create_blaze_cake','cmr:mixing/frozen_cake',
    'botania:mana_infusion/ice','avaritia:dense_neutron_compressor','avaritia:denser_neutron_compressor','avaritia:densest_neutron_compressor','avaritia:infinity_catalyst',
    'avaritia:infinity_catalyst_eternal','avaritia:ancient_debris_eight','avaritia:upgrade_smithing_template_too','minecraft:echo_shard','ifeu:infuser/sculk',
    'powah:energizing/ender_core']

  const types = ['botania:orechid','botania:orechid_ignem','expatternprovider:circuit_cutter','industrialforegoing:fluid_extractor']

  const outputs = ['botania:runic_altar','projecte:philosophers_stone','projecte:dark_matter','projecte:red_matter','projecte:dm_helmet','projecte:dm_chestplate','projecte:dm_leggings',
    'projecte:dm_boots','emc_interface:emc_interface','projecte:transmutation_tablet','projecte:transmutation_table','thermal:rubber','powah:dielectric_paste','ifeu:chance_addon_1',
    'ifeu:chance_addon_2','ifeu:chance_addon_3','ifeu:chance_addon_4','ifeu:chance_addon_5','ifeu:chance_addon_6','ifeu:creative_chance_addon','ifeu:silk_addon','ifeu:creative_capacitor',
    'ifeu:rule_controller','ifeu:fluid_transfer','ifeu:precision_crafting_table','ifeu:platform_builder']

  ids.forEach(RemoveID); types.forEach(RemoveType); outputs.forEach(RemoveOutput)
})
