ServerEvents.recipes(event => {

    event.shaped(Item.of('botania:alchemy_catalyst', 1),['ABA','BCB','ABA'],{A:'botania:livingrock',B:'minecraft:gold_ingot',  C:'botania:mana_diamond'})
    event.shaped(Item.of('kubejs:compressed_draconium_core', 1),['ABA','BCB','ABA'],{A:'draconicevolution:draconium_block',B:'minecraft:gold_block',  C:'minecraft:diamond_block'})
    event.shaped(Item.of('kubejs:compressed_wyvern_core', 1),['ABA','BCB','ABA'],{A:'draconicevolution:draconium_block',B:'kubejs:compressed_draconium_core',  C:'extendedcrafting:nether_star_block'})
    event.shaped(Item.of('kubejs:terrestrial_catalyst', 2),['ABA','BAB','ABA'],{A:'botania:terrasteel_nugget',B:'botania:alchemy_catalyst'})
    event.shaped(Item.of('botania:alfheim_portal', 1),['ABA','ACA','ADA'],{A:'botania:livingwood_log',B:'botania:terrasteel_ingot',C:'projecte:philosophers_stone',D:'botania:glimmering_livingwood_log'})
    event.shaped(Item.of('projecte:dm_helmet', 1),['AAA','ABA','   '],{A:'projecte:dark_matter',B:'botania:life_essence'})
    event.shaped(Item.of('mekanism:cardboard_box', 1),['AAA','A A','AAA'],{A:'create:cardboard'})
    event.shaped(Item.of('minecraft:chest', 4),['AAA','A A','AAA'],{A:'#minecraft:logs'})
    event.shaped(Item.of('projecte:dm_chestplate', 1),['ABA','AAA','AAA'],{A:'projecte:dark_matter',B:'botania:life_essence'})
    event.shaped(Item.of('projecte:dm_leggings', 1),['AAA','ABA','A A'],{A:'projecte:dark_matter',B:'botania:life_essence'})
    event.shaped(Item.of('projecte:dm_boots', 1),['ABA','A A','   '],{A:'projecte:dark_matter',B:'botania:life_essence'})
    event.shaped(Item.of('projecte:iron_band', 1),['AAA','ABA','AAA'],{A:'minecraft:iron_ingot',B:'botania:life_essence'})
    event.shaped(Item.of('projecte:transmutation_table', 1),['ABA','CDC','ABA'],{A:'botania:dragonstone',B:'minecraft:crying_obsidian',C:'projecte:dark_matter',D:'projecte:philosophers_stone'})
    event.shaped(Item.of('entangled:block', 1),['ABA','BCB','ABA'],{A:'pneumaticcraft:smooth_plastic_brick_magenta',B:'rftoolsbase:infused_enderpearl',C:'thermal:enderium_gear'})
    event.shaped(Item.of('kubejs:capacitor_ender', 1),['ADA','BCB','ADA'],{A:'powah:dielectric_paste',B:'kubejs:sculk_ingot',C:'powah:capacitor_basic_large',D:'thermal:enderium_ingot'})
    event.shaped(Item.of('gag:time_sand_pouch', 1),['ABC','DED','DDD'],{A:'projecte:low_covalence_dust',B:'projecte:medium_covalence_dust',C:'projecte:high_covalence_dust',D:'minecraft:leather',E:'minecraft:ender_eye'})

    function Addon(module,addon) {event.shaped(addon,['ABA','ACA','ABA'],{A:'minecraft:iron_ingot',B:'pneumaticcraft:plastic',C:module})}
    Addon('kubejs:t1apple','ifeu:apple_addon_1')
    Addon('kubejs:t1thread','ifeu:thread_addon_1')
    Addon('kubejs:t1heal','ifeu:heal_addon_1')
    Addon('kubejs:t1eff',Item.of('industrialforegoing:efficiency_addon_1', '{TitaniumAugment:{Efficiency:0.9f}}'))
    Addon('kubejs:t1proc',Item.of('industrialforegoing:processing_addon_1', '{TitaniumAugment:{Processing:2.0f}}'))
    Addon('kubejs:t1speed',Item.of('industrialforegoing:speed_addon_1', '{TitaniumAugment:{Speed:2.0f}}'))
    Addon('kubejs:t2apple','ifeu:apple_addon_2')
    Addon('kubejs:t2thread','ifeu:thread_addon_2')
    Addon('kubejs:t2heal','ifeu:heal_addon_2')
    Addon('kubejs:t2eff',Item.of('industrialforegoing:efficiency_addon_2', '{TitaniumAugment:{Efficiency:0.8f}}'))
    Addon('kubejs:t2proc',Item.of('industrialforegoing:processing_addon_2', '{TitaniumAugment:{Processing:3.0f}}'))
    Addon('kubejs:t2speed',Item.of('industrialforegoing:speed_addon_2', '{TitaniumAugment:{Speed:3.0f}}'))
    Addon('kubejs:t3apple','ifeu:apple_addon_3')
    Addon('kubejs:t3thread','ifeu:thread_addon_3')
    Addon('kubejs:t3heal','ifeu:heal_addon_3')
    Addon('kubejs:t3eff',Item.of('ifeu:efficiency_addon_3', '{TitaniumAugment:{Efficiency:0.7f}}'))
    Addon('kubejs:t3proc',Item.of('ifeu:processing_addon_3', '{TitaniumAugment:{Processing:4.0f}}'))
    Addon('kubejs:t3speed',Item.of('ifeu:speed_addon_3', '{TitaniumAugment:{Speed:4.0f}}'))
    Addon('kubejs:t4apple','ifeu:apple_addon_4')
    Addon('kubejs:t4thread','ifeu:thread_addon_4')
    Addon('kubejs:t4heal','ifeu:heal_addon_4')
    Addon('kubejs:t4eff',Item.of('ifeu:efficiency_addon_4', '{TitaniumAugment:{Efficiency:0.6f}}'))
    Addon('kubejs:t4proc',Item.of('ifeu:processing_addon_4', '{TitaniumAugment:{Processing:5.0f}}'))
    Addon('kubejs:t4speed',Item.of('ifeu:speed_addon_4', '{TitaniumAugment:{Speed:7.0f}}'))
    Addon('kubejs:t5apple','ifeu:apple_addon_5')
    Addon('kubejs:t5thread','ifeu:thread_addon_5')
    Addon('kubejs:t5heal','ifeu:heal_addon_5')
    Addon('kubejs:t5eff',Item.of('ifeu:efficiency_addon_5', '{TitaniumAugment:{Efficiency:0.5f}}'))
    Addon('kubejs:t5proc',Item.of('ifeu:processing_addon_5', '{TitaniumAugment:{Processing:6.0f}}'))
    Addon('kubejs:t5speed',Item.of('ifeu:speed_addon_5', '{TitaniumAugment:{Speed:21.0f}}'))
    Addon('kubejs:t6apple','ifeu:apple_addon_6')
    Addon('kubejs:t6thread','ifeu:thread_addon_6')
    Addon('kubejs:t6heal','ifeu:heal_addon_6')
    Addon('kubejs:t6eff',Item.of('ifeu:efficiency_addon_6', '{TitaniumAugment:{Efficiency:0.39999998f}}'))
    Addon('kubejs:t6proc',Item.of('ifeu:processing_addon_6', '{TitaniumAugment:{Processing:7.0f}}'))
    Addon('kubejs:t6speed',Item.of('ifeu:speed_addon_6', '{TitaniumAugment:{Speed:101.0f}}'))
    Addon('kubejs:t1range',Item.of('industrialforegoing:range_addon0', '{TitaniumAugment:{Range:0.0f}}'))
    Addon('kubejs:t2range',Item.of('industrialforegoing:range_addon1', '{TitaniumAugment:{Range:1.0f}}'))
    Addon('kubejs:t3range',Item.of('industrialforegoing:range_addon2', '{TitaniumAugment:{Range:2.0f}}'))
    Addon('kubejs:t4range',Item.of('industrialforegoing:range_addon3', '{TitaniumAugment:{Range:3.0f}}'))
    Addon('kubejs:t5range',Item.of('industrialforegoing:range_addon4', '{TitaniumAugment:{Range:4.0f}}'))
    Addon('kubejs:t6range',Item.of('industrialforegoing:range_addon5', '{TitaniumAugment:{Range:5.0f}}'))
    Addon('kubejs:t7range',Item.of('industrialforegoing:range_addon6', '{TitaniumAugment:{Range:6.0f}}'))
    Addon('kubejs:t8range',Item.of('industrialforegoing:range_addon7', '{TitaniumAugment:{Range:7.0f}}'))
    Addon('kubejs:t9range',Item.of('industrialforegoing:range_addon8', '{TitaniumAugment:{Range:8.0f}}'))
    Addon('kubejs:t10range',Item.of('industrialforegoing:range_addon9', '{TitaniumAugment:{Range:9.0f}}'))
    Addon('kubejs:t11range',Item.of('industrialforegoing:range_addon10', '{TitaniumAugment:{Range:10.0f}}'))
    Addon('kubejs:t12range',Item.of('industrialforegoing:range_addon11', '{TitaniumAugment:{Range:11.0f}}'))
  })