ServerEvents.recipes(event => {

  function createCompressionRecipes(item, block) {event.shapeless(block, Array(9).fill(item));event.shapeless(Item.of(item, 9), [block])}
  const compressionPairs = [
    ['minecraft:blaze_rod', 'kubejs:blaze_rod_block'],['thermal:ruby', 'thermal:ruby_block'],['thermal:sapphire', 'thermal:sapphire_block'],
    ['kubejs:sculk_ingot', 'kubejs:sculk_metal_block'],['thermal:diamond_dust', 'kubejs:diamond_sand'],['thermal:emerald_dust', 'kubejs:emerald_sand'],
    ['thermal:sulfur_dust', 'kubejs:sulfur_sand'],['thermal:niter_dust', 'kubejs:niter_sand'],['kubejs:time_token', 'kubejs:advance_time_token'],
    ['kubejs:advance_time_token', 'kubejs:ultimate_time_token'],['minecraft:flint', 'kubejs:flint_block'],['minecraft:sculk', 'kubejs:compressed_sculk'],
    ['minecraft:amethyst_block', 'kubejs:compressed_amethyst_block'],['kubejs:chromatic_compound', 'kubejs:chromatic_block'],
    ['minecraft:stick', 'kubejs:stick_block'],['minecraft:clay', 'kubejs:compressed_clay'],['minecraft:ender_pearl', 'kubejs:ender_pearl_block'],
    ['minecraft:glowstone_dust', 'kubejs:dense_glowstone'],['minecraft:prismarine_crystals', 'kubejs:prismarine_crystal_block'],['minecraft:andesite', 'kubejs:compressed_andesite'],
    ['minecraft:chorus_fruit', 'kubejs:chorus_block'],['mekanism:dust_obsidian', 'kubejs:obsidian_sand'],['create:polished_rose_quartz', 'kubejs:polish_rose_quartz_block'],
    ['draconicevolution:draconium_core', 'kubejs:compressed_draconium_core'],['draconicevolution:wyvern_core', 'kubejs:compressed_wyvern_core'],
    ['draconicevolution:awakened_core', 'kubejs:compressed_awakened_core'],['draconicevolution:chaotic_core', 'kubejs:compressed_chaotic_core']]
  compressionPairs.forEach(function(pair) {createCompressionRecipes(pair[0], pair[1])})

event.shapeless('create:rose_quartz', ['ae2:certus_quartz_crystal','8x minecraft:redstone'])
event.shapeless('botania:glimmering_livingwood_log', ['projecte:low_covalence_dust','botania:livingwood_log'])
event.shapeless('minecraft:coal_block', ['projecte:philosophers_stone','4x thermal:charcoal_block'])
event.shapeless('projecte:alchemical_coal_block', ['projecte:philosophers_stone','4x minecraft:coal_block'])
event.shapeless('projecte:mobius_fuel_block', ['projecte:philosophers_stone','4x projecte:alchemical_coal_block'])
event.shapeless('projecte:aeternalis_fuel_block', ['projecte:philosophers_stone','4x projecte:mobius_fuel_block'])
event.shapeless('4x projecte:mobius_fuel_block', ['projecte:philosophers_stone','projecte:aeternalis_fuel_block'])
event.shapeless('4x projecte:alchemical_coal_block', ['projecte:philosophers_stone','projecte:mobius_fuel_block'])
event.shapeless('4x minecraft:coal_block', ['projecte:philosophers_stone','projecte:alchemical_coal_block'])
event.shapeless('4x thermal:charcoal_block', ['projecte:philosophers_stone','minecraft:coal_block'])
event.shapeless('thermal:frost_melon_slice', ['minecraft:melon_slice','projecte:zero_ring'])
event.shapeless('4x minecraft:clay_ball', ['minecraft:clay'])
event.shapeless('minecraft:skeleton_skull', 'minecraft:zombie_head')
event.shapeless('minecraft:skeleton_skull', 'minecraft:creeper_head')
event.shapeless('4x minecraft:snowball', ['minecraft:snow_block'])
event.shapeless('draconicevolution:crafting_core', ['draconicevolution:crafting_core'])
event.shapeless('appbot:creative_mana_cell', ['appbot:mana_cell_housing','kubejs:cell_component_creative'])
event.shapeless('appmek:creative_chemical_cell', ['appmek:chemical_cell_housing','kubejs:cell_component_creative'])
event.shapeless('ae2:creative_item_cell', ['ae2:item_cell_housing','kubejs:cell_component_creative'])
event.shapeless('ae2:creative_fluid_cell', ['ae2:fluid_cell_housing','kubejs:cell_component_creative'])
event.shapeless('mekanism:creative_chemical_tank', ['mekanism:creative_chemical_tank'])
event.shapeless('mekanism:creative_fluid_tank', ['mekanism:creative_fluid_tank'])
event.shapeless('kubejs:incomplete_rough_star', ['kubejs:incomplete_rough_star'])
event.shapeless('kubejs:dense_redstone_block',['4x minecraft:redstone_block'])
event.shapeless('kubejs:glowing_obsidian_sand', ['kubejs:obsidian_sand', 'kubejs:dense_glowstone'])
event.shapeless('4x kubejs:dense_glowstone',['9x minecraft:glowstone'])
event.shapeless('64x kubejs:ultimate_time_token',['kubejs:creative_time_token'])
event.shapeless('minecraft:netherite_ingot',['4x minecraft:netherite_scrap', '4x minecraft:gold_ingot'])
event.shapeless('kubejs:t1apple', ['ifeu:apple_addon_1'])
event.shapeless('kubejs:t2apple', ['ifeu:apple_addon_2'])
event.shapeless('kubejs:t3apple', ['ifeu:apple_addon_3'])
event.shapeless('kubejs:t4apple', ['ifeu:apple_addon_4'])
event.shapeless('kubejs:t5apple', ['ifeu:apple_addon_5'])
event.shapeless('kubejs:t6apple', ['ifeu:apple_addon_6'])
event.shapeless('kubejs:t1thread', ['ifeu:thread_addon_1'])
event.shapeless('kubejs:t2thread', ['ifeu:thread_addon_2'])
event.shapeless('kubejs:t3thread', ['ifeu:thread_addon_3'])
event.shapeless('kubejs:t4thread', ['ifeu:thread_addon_4'])
event.shapeless('kubejs:t5thread', ['ifeu:thread_addon_5'])
event.shapeless('kubejs:t6thread', ['ifeu:thread_addon_6'])
event.shapeless('kubejs:t1heal', ['ifeu:heal_addon_1'])
event.shapeless('kubejs:t2heal', ['ifeu:heal_addon_2'])
event.shapeless('kubejs:t3heal', ['ifeu:heal_addon_3'])
event.shapeless('kubejs:t4heal', ['ifeu:heal_addon_4'])
event.shapeless('kubejs:t5heal', ['ifeu:heal_addon_5'])
event.shapeless('kubejs:t6heal', ['ifeu:heal_addon_6'])
event.shapeless('kubejs:t1eff', [Item.of('industrialforegoing:efficiency_addon_1', '{TitaniumAugment:{Efficiency:0.9f}}')])
event.shapeless('kubejs:t2eff', [Item.of('industrialforegoing:efficiency_addon_2', '{TitaniumAugment:{Efficiency:0.8f}}')])
event.shapeless('kubejs:t3eff', [Item.of('ifeu:efficiency_addon_3', '{TitaniumAugment:{Efficiency:0.7f}}')])
event.shapeless('kubejs:t4eff', [Item.of('ifeu:efficiency_addon_4', '{TitaniumAugment:{Efficiency:0.6f}}')])
event.shapeless('kubejs:t5eff', [Item.of('ifeu:efficiency_addon_5', '{TitaniumAugment:{Efficiency:0.5f}}')])
event.shapeless('kubejs:t6eff', [Item.of('ifeu:efficiency_addon_6', '{TitaniumAugment:{Efficiency:0.39999998f}}')])
event.shapeless('kubejs:t1proc', [Item.of('industrialforegoing:processing_addon_1', '{TitaniumAugment:{Processing:2.0f}}')])
event.shapeless('kubejs:t2proc', [Item.of('industrialforegoing:processing_addon_2', '{TitaniumAugment:{Processing:3.0f}}')])
event.shapeless('kubejs:t3proc', [Item.of('ifeu:processing_addon_3', '{TitaniumAugment:{Processing:4.0f}}')])
event.shapeless('kubejs:t4proc', [Item.of('ifeu:processing_addon_4', '{TitaniumAugment:{Processing:5.0f}}')])
event.shapeless('kubejs:t5proc', [Item.of('ifeu:processing_addon_5', '{TitaniumAugment:{Processing:6.0f}}')])
event.shapeless('kubejs:t6proc', [Item.of('ifeu:processing_addon_6', '{TitaniumAugment:{Processing:7.0f}}')])
event.shapeless('kubejs:t1speed', [Item.of('industrialforegoing:speed_addon_1', '{TitaniumAugment:{Speed:2.0f}}')])
event.shapeless('kubejs:t2speed', [Item.of('industrialforegoing:speed_addon_2', '{TitaniumAugment:{Speed:3.0f}}')])
event.shapeless('kubejs:t3speed', [Item.of('ifeu:speed_addon_3', '{TitaniumAugment:{Speed:4.0f}}')])
event.shapeless('kubejs:t4speed', [Item.of('ifeu:speed_addon_4', '{TitaniumAugment:{Speed:7.0f}}')])
event.shapeless('kubejs:t5speed', [Item.of('ifeu:speed_addon_5', '{TitaniumAugment:{Speed:21.0f}}')])
event.shapeless('kubejs:t6speed', [Item.of('ifeu:speed_addon_6', '{TitaniumAugment:{Speed:101.0f}}')])
event.shapeless('kubejs:t1range', [Item.of('industrialforegoing:range_addon0', '{TitaniumAugment:{Range:0.0f}}')])
event.shapeless('kubejs:t2range', [Item.of('industrialforegoing:range_addon1', '{TitaniumAugment:{Range:1.0f}}')])
event.shapeless('kubejs:t3range', [Item.of('industrialforegoing:range_addon2', '{TitaniumAugment:{Range:2.0f}}')])
event.shapeless('kubejs:t4range', [Item.of('industrialforegoing:range_addon3', '{TitaniumAugment:{Range:3.0f}}')])
event.shapeless('kubejs:t5range', [Item.of('industrialforegoing:range_addon4', '{TitaniumAugment:{Range:4.0f}}')])
event.shapeless('kubejs:t6range', [Item.of('industrialforegoing:range_addon5', '{TitaniumAugment:{Range:5.0f}}')])
event.shapeless('kubejs:t7range', [Item.of('industrialforegoing:range_addon6', '{TitaniumAugment:{Range:6.0f}}')])
event.shapeless('kubejs:t8range', [Item.of('industrialforegoing:range_addon7', '{TitaniumAugment:{Range:7.0f}}')])
event.shapeless('kubejs:t9range', [Item.of('industrialforegoing:range_addon8', '{TitaniumAugment:{Range:8.0f}}')])
event.shapeless('kubejs:t10range', [Item.of('industrialforegoing:range_addon9', '{TitaniumAugment:{Range:9.0f}}')])
event.shapeless('kubejs:t11range', [Item.of('industrialforegoing:range_addon10', '{TitaniumAugment:{Range:10.0f}}')])
event.shapeless('kubejs:t12range', [Item.of('industrialforegoing:range_addon11', '{TitaniumAugment:{Range:11.0f}}')])

})
