#KubeJS Client Properties
#Sat Apr 26 15:16:28 CST 2025
backgroundColor=2E3440
barBorderColor=ECEFF4
exportAtlases=false
menuBackgroundBrightness=64
disableRecipeBook=false
title=神话：起源-通往神界的大门就在面前，门缝中渗出亿万道绞缠的星轨，同时传来了冰冷的声音：“登神者，请剜出心脏称重。”
barColor=ECEFF4
overrideColors=false
fmlLogColor=ECEFF4
showTagNames=false
fmlMemoryColor=ECEFF4
menuBackgroundScale=32.0
blurScaledPackIcon=true
menuInnerBackgroundBrightness=32
