ServerEvents.recipes(event => {
    event.remove({ id: 'sophisticatedbackpacks:feeding_upgrade' })
    event.remove({ id: 'sophisticatedbackpacks:advanced_feeding_upgrade' })
    event.remove({ id: 'sophisticatedstorage:feeding_upgrade' })
    event.remove({ id: 'sophisticatedstorage:advanced_feeding_upgrade' })
    event.remove({ id: 'sophisticatedstorage:stack_upgrade_omega_tier' })
    event.remove({ id: 'sophisticatedbackpacks:stack_upgrade_omega_tier' })
    event.remove({ id: 'sophisticatedstorage:compacting_upgrade' })
    event.remove({ id: 'sophisticatedstorage:advanced_compacting_upgrade' })
    event.remove({ id: 'sophisticatedbackpacks:compacting_upgrade' })
    event.remove({ id: 'sophisticatedbackpacks:advanced_compacting_upgrade' })
    event.remove({ output: 'sophisticatedstorage:storage_output' })
    event.remove({ output: 'sophisticatedstorage:storage_input' })
    event.remove({ output: 'sophisticatedstorage:controller' })
    event.remove({ output: 'sophisticatedstorage:storage_link' })
    event.remove({ output: 'sophisticatedstorage:storage_io' })
})