StartupEvents.registry('fluid', event => {

    event.create('mana_oil').thinTexture(0x9913BD).bucketColor(0x9913BD).displayName('Mana Oil')
    event.create('water_oil').thinTexture(0x1331BD).bucketColor(0x1331BD).displayName('Water Oil')
    event.create('fire_oil').thinTexture(0xF2870B).bucketColor(0xF2870B).displayName('Fire Oil')
    event.create('air_oil').thinTexture(0x8fedfe).bucketColor(0x8fedfe).displayName('Air Oil')
    event.create('earth_oil').thinTexture(0x1FAC0E).bucketColor(0x1FAC0E).displayName('Earth Oil')
    event.create('impure_brass').thickTexture(0xf3ac30).bucketColor(0xf3ac30).displayName('Impure Brass')
    event.create('gaia_essence').thickTexture(0x9e91cc).bucketColor(0x9e91cc).displayName('Gaia Essence')
    event.create('liquid_nitrogen').thinTexture(0xf0fffe).bucketColor(0xf0fffe).displayName('Liquid Nitrogen')
    event.create('molten_awakened_draconium').thickTexture(0xFF6A00).bucketColor(0xFF6A00).displayName('Molten Awakened Draconium')
    event.create('destabilized_star').thickTexture(0xf1ff96).bucketColor(0xf1ff96).displayName('Destabilized Star')
    event.create('molten_lapis').thickTexture(0x0059ff).bucketColor(0x0059ff).displayName('Molten Lapis')
    event.create('glow_ink').thinTexture(0x00302e).bucketColor(0x00302e).displayName('Glow Ink')
    event.create('enchanted_lapis').thickTexture(0x3200ff).bucketColor(0x3200ff).displayName('Enchanted lapis')
    event.create('artificial_hyper_experience').thickTexture(0x1DFFED).bucketColor(0x1DFFED).displayName('Artificial Hyper Experience')
    event.create('frost_melon_juice').thinTexture(0xc5e7ff).bucketColor(0xc5e7ff).displayName('Frost Melon Juice')
    event.create('corium').thickTexture(0x504332).bucketColor(0x504332).displayName('Corium')

})