
#Common Configs
[common]
	#If true, use whitelist, if false, use blacklist
	InvulnerableItem = true
	#The items in the list are Invulnerable
	WhitelistItems = []
	#The items in the list are not Invulnerable
	BlacklistItems = []
	#If true, you could clean all items
	CleanAll = false
	#If true, clear items scheduled
	ClearSchedule = true
	#Clean time
	#Range: > 0
	CleanTime = 2400

