
[world_creation_settings]
	#The directory of the world template
	template_directory = "template"
	#Whether a template should be used instead of creating regular worlds
	use_template = true

[world_creation_menu_settings]
	#Toggle the world tab
	disable_world_tab = true

[main_menu_settings]
	#Toggle the multiplayer button
	disable_multiplayer = false
	#Toggle the singleplayer button
	disable_singleplayer = false

