
["Boss Health"]
	#Health for specified mob.
	"Gob, King of Gnomes Health" = 6300.0
	#Health for specified mob.
	"Super Sniffer Health" = 7600.0
	#Health for specified mob.
	"Ultra Sniffer Health" = 1500.0
	#Health for specified mob.
	"Trial Guardian Health" = 7300.0
	#Health for specified mob.
	"Virtue Health" = 8000.0
	#Health for specified mob.
	"Enchanter Merlin Health" = 7000.0
	#Health for specified mob.
	"Sorceress Circe Health" = 6800.0
	#Health for specified mob.
	"Archmage Gundalf Health" = 9000.0
	#Health for specified mob.
	"Multiplayer Boss Health Scaling" = true

["Mob Health"]
	#Health for specified mob.
	"Duskrok Health" = 6000.0
	#Health for specified mob.
	"Hellrok Health" = 7000.0

[Bosses]
	#If true, Terramity bosses will despawn after you die.
	"Can Bosses Despawn" = true

["Mob Griefing"]
	#If false, Terramity mobs will (mostly) not damage terrain.
	MobGriefing = true

