ServerEvents.recipes(event => {
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_charcoal_block' })
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_coal' })
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_charcoal' })
    event.remove({ id: 'mekanism:infusion_conversion/carbon/from_coal_block' })
    event.remove({ id: 'mekanism:cardboard_box' })
    event.remove({ id: 'mekanism:sawing/bamboo_block' })
    event.remove({ id: 'mekanism:control_circuit/advanced' })
    event.remove({ id: 'mekanism:control_circuit/basic' })
    event.remove({ id: 'mekanism:processing/refined_glowstone/ingot/from_dust' })
    event.remove({ id: 'tconstruct:compat/refined_glowstone_ingot' })
    event.remove({ id: 'mekanism:control_circuit/elite' })
    event.remove({ id: 'mekanism:sps_casing' })
    event.remove({ id: 'mekanism:control_circuit/ultimate' })
    event.remove({ id: 'mekanism:teleportation_core' })
    event.remove({ id: 'tconstruct:smeltery/alloys/molten_refined_obsidian' })
})