ServerEvents.recipes(event => {
    event.remove({ id: 'bloodmagic:blood_rune_blank' })
    event.remove({ id: 'bloodmagic:altar/magicianbloodorb' })
    event.remove({ id: 'bloodmagic:altar/air_tool' })
    event.remove({ id: 'bloodmagic:altar/fire_tool' })
    event.remove({ id: 'bloodmagic:altar/water_tool' })
    event.remove({ id: 'bloodmagic:altar/earth_tool' })
    event.remove({ id: 'bloodmagic:altar/dusk_tool' })
    event.remove({ id: 'bloodmagic:sacrificial_dagger' })
    event.remove({ id: 'bloodmagic:altar/daggerofsacrifice' })
    event.remove({ id: 'bloodmagic:altar/archmagebloodorb' })
    event.remove({ id: 'bloodmagic:alchemytable/arcane_ash' })
    event.remove({ id: 'bloodmagic:alchemytable/reagent_water' })
    event.remove({ id: 'bloodmagic:alchemytable/reagent_sight' })
    event.remove({ id: 'bloodmagic:alchemytable/reagent_lava' })
    event.remove({ id: 'bloodmagic:alchemytable/reagent_air' })
    event.remove({ id: 'bloodmagic:arc/weakbloodshard_tau' })
    event.remove({ id: 'bloodmagic:arc/reversion/master_blood_orb' })
    event.remove({ id: 'bloodmagic:alchemytable/reagent_teleposition' })
    event.remove({ id: 'bloodmagic:alchemytable/reagent_void' })
    event.remove({ id: 'bloodmagic:alchemytable/reagent_suppression' })
})